image: node:20

stages:
  - build
  - deploy

variables:
  NODE_ENV: production

cache:
  paths:
    - node_modules/

build:
  stage: build
  script:
    - npm ci

deploy:
  stage: deploy
  script:
    - npm ci --omit=dev
    - npm start
  only:
    - main
